apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../manual
patchesStrategicMerge:
  - awscluster-vpc-spec.yaml
  - cp-machinetemplate.yaml
  - wkr-machinetemplate.yaml
